services:
  demo.web:
    image: demo.web
    hostname: demo
    build:
      context: .
      dockerfile: src/Demo.Web/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    hostname: otel
    volumes:
      - ./provisioning/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: [ "--config", "/etc/otel-collector-config.yaml" ]
    depends_on:
      - tempo
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/config.yml" ]
    volumes:
      - loki-data:/loki
      - ./provisioning/loki/config.yml:/etc/loki/config.yml:ro
      - ./provisioning/loki/rules:/etc/loki/rules/fake

  tempo:
    image: grafana/tempo:latest
    command: [ "--config.file=/etc/tempo.yml" ]
    volumes:
      - tempo-data:/var/tempo
      - ./provisioning/tempo.yml:/etc/tempo.yml

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./provisioning/prometheus/config.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./provisioning/prometheus/rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./provisioning/alertmanager-config.yml:/etc/alertmanager/config.yml:ro
    command:
      - --config.file=/etc/alertmanager/config.yml

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5000:80"
      - "2525:25"

volumes:
  grafana-data:
  loki-data:
  tempo-data:
