global:
  smtp_smarthost: 'smtp4dev:25'
  smtp_from: 'alerts@example.com'
  smtp_require_tls: false

route:
  receiver: email-alerts
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: email-alerts
    email_configs:
      - to: 'you@example.com'
        send_resolved: true