receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"

  otlp:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/logs]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
  